branches:
  - master
  - name: beta
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - 
    - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - 
    - "@semantic-release/github"
    - assets:
        - "CHANGELOG.md"
        - "dist/**"
      message: "chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - 
    - "@semantic-release/git"
    - assets:
        - "package.json"
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

# branches:
#   - master
#   - name: beta
#     prerelease: true

# plugins:
#   - '@semantic-release/commit-analyzer'
#   - '@semantic-release/release-notes-generator'
#   - - '@semantic-release/changelog'
#     - changelogFile: 'CHANGELOG.md'
#   - - '@semantic-release/github'
#     - assets:
#         - 'CHANGELOG.md'
#   - - '@semantic-release/git'
#     - assets:
#         - 'CHANGELOG.md'
#         - 'dist/**'
#       message: 'chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'